homebrew_taps:
  - buildkite/buildkite
  - buildkite/cli
  - caskroom/fonts
  - heroku/brew
  - homebrew/cask
  - exolnet/homebrew-deprecated
  - rockymadden/rockymadden
  - caffix/amass

homebrew_packages:
  - bk
  - buildkite-agent
  - dnsmasq
  - figlet
  - gdal
  - gh
  - git
  - git-lfs
  - heroku
  - hugo
  - jq
  - jrnl
  - lastpass-cli
  - libgeoip
  - mariadb
  - mpv
  - nginx
  - nmap
  - php
  - php@7.4
  - pipenv
  - postgis
  - postgresql
  - pwgen
  - python
  - rbenv
  - redis
  - ruby
  - slack-cli
  - speedtest-cli
  - tree

homebrew_package_removals: []

homebrew_cask_packages:
  - ableton-live-standard9
  - adobe-creative-cloud
  - amass
  - cyberduck
  - discord
  - docker
  - element
  - eloston-chromium
  - epic-games
  - expressvpn
  - figma
  - firefox
  - flux
  - font-fira-code
  - github
  - insomnia
  - iterm2
  - keybase
  - linear-linear
  - missive
  - ngrok
  - notion
  - nvalt
  - signal
  - sizzy
  - sketch
  - skype
  - slack
  - spectacle
  - spotify
  - steam
  - tableplus
  - telegram
  - transmission
  - twist
  - universal-media-server
  - vagrant
  - virtualbox
  - visual-studio-code
  - vivaldi
  - vlc
  - whatsapp
  - zoomus

homebrew_cask_removals: []
