#!/usr/bin/env ansible-playbook
- hosts: 127.0.0.1
  connection: local
  vars:
   ansible_python_interpreter: /usr/bin/python3
  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/mac-ansible')

- hosts: 127.0.0.1
  connection: local
  vars:
   ansible_python_interpreter: /usr/bin/python3
  roles:
  - mac
