- stat:
    path: "{{ visual_studio_code_settings_path }}"
  register: visual_studio_code_settings_file
  tags:
    - visual_studio_code
    - settings

- name: Remove Visual Studio Code settings.json if not symlink
  file:
    path: "{{ visual_studio_code_settings_path }}"
    state: absent
  when: visual_studio_code_settings_file.stat.islnk is defined and visual_studio_code_settings_file.stat.islnk == False
  tags:
    - visual_studio_code
    - settings

- name: Visual Studio Code settings in place
  file:
    src: "{{ role_path }}/files/visual_studio_code/settings.json"
    dest: "{{ visual_studio_code_settings_path }}"
    state: link
  tags:
    - visual_studio_code
    - settings

- name: Visual Studio Code extensions installed
  visual_studio_code_install_extension:
    name: "{{ item }}"
  loop: "{{ visual_studio_code_extensions }}"
  tags:
    - visual_studio_code
    - settings
    - extensions
