- name: Add Homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"
  tags:
    - brew
    - installs

- name: Update Homebrew
  homebrew:
    update_homebrew: yes
  tags:
    - brew
    - installs

- name: Uninstall Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: absent
  loop: "{{ homebrew_package_removals }}"
  tags:
    - brew
    - installs

- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: latest
  loop: "{{ homebrew_packages }}"
  tags:
    - brew
    - installs

- name: Uninstall Homebrew Casks
  homebrew_cask:
    name: "{{ item }}"
    state: absent
  loop: "{{ homebrew_cask_removals }}"
  tags:
    - brew
    - cask
    - installs

- name: Install Homebrew Cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=/Applications"
  loop: "{{ homebrew_cask_packages }}"
  tags:
    - brew
    - cask
    - installs
