- name: Setup SSH
  import_tasks: ssh.yml

- name: Install software
  import_tasks: installs.yml
  tags:
    - brew
    - installs

- name: Install and setup development environments
  import_tasks: development_environments.yml
  tags:
    - installs

- name: Set application settings
  import_tasks: application_settings.yml

- name: Setup OSX defaults
  import_tasks: osx_settings.yml

- name: Setup shell
  import_tasks: shell.yml
  tags:
    - shell
