# Requires root to run. Disable for the moment.
# - name: Change shell to ZSH
#   shell: chsh -s /bin/zsh

- name: Install zsh-nvm to make NVM and ZSH interop easier
  git:
    repo: https://github.com/lukechilds/zsh-nvm.git
    dest: ~/.zsh-nvm
    update: yes
- name: Dotfiles in place
  file:
    src: "{{ role_path }}/files/dotfiles/{{ item }}"
    path: "~/.{{ item }}"
    state: link
  loop:
    - zshrc
