# Regular key bindings
bindkey "^K" kill-whole-line
bindkey "^R" history-incremental-search-backward
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

# Run git status
alias s='git status'

# Run git log
alias l='git log'

# Reload .zshrc
function zr () {
  source $HOME/.zshrc
}

function killport () {
  lsof -i TCP:$1 | grep LISTEN | awk '{print $2}' | xargs kill -9
}

function internet {
  if (ping -c 3 -t 3 google.com > /dev/null 2>&1)
  then
    echo 'Internet available.'
  else
    echo 'No internet up.'
  fi
}

# Ensure NVM works correctly
source ~/.zsh-nvm/zsh-nvm.plugin.zsh

# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship

export SPACESHIP_CHAR_SYMBOL="> "
export SPACESHIP_TIME_SHOW=true
export SPACESHIP_HOST_SHOW=true
export SPACESHIP_USER_SHOW=needed
export SPACESHIP_USER_PREFIX=''
export SPACESHIP_DIR_PREFIX=''

export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export PATH="/usr/local/opt/icu4c/bin:$PATH"

export PATH="/usr/local/opt/php@7.4/bin:$PATH"

HISTFILE="$HOME/.zsh_history"
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
export HISTTIMEFORMAT="[%F %T] " # Set specific history format
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

# Ruby
eval "$(rbenv init -)"

# Python
alias python=/usr/local/bin/python3 
