homebrew_taps:
  - homebrew/cask
  - caskroom/fonts

homebrew_package_removals: []

homebrew_packages:
  - git
  - lastpass-cli
  - pwgen
  - python
  - tree

homebrew_cask_removals: []

homebrew_cask_packages:
  - abstract
  - airmail-beta
  - docker
  - expressvpn
  - firefox
  - flux
  - font-fira-code
  - github
  - google-chrome
  - iterm2
  - keybase
  - libreoffice
  - signal
  - slack
  - spectacle
  - spotify
  - steam
  - tableplus
  - transmission
  - virtualbox
  - visual-studio-code
  - vlc
  - whatsapp

pip_packages: []

nodejs_versions:
  # Maximum version available on AWS Lambda
  - v8.10
  # Current LTS
  - v10.15
  # Current version
  - v11.6

visual_studio_code_config_path: Library/Application Support/Code
visual_studio_code_settings_path: "~{{ ansible_user }}/{{ visual_studio_code_config_path }}/User/settings.json"

visual_studio_code_extensions:
  - ms-python.python
  - vscoss.vscode-ansible
  - esbenp.prettier-vscode
